### ISSUE TITLE
Alternative for `parted mkfs` needed.

### ISSUE THREAD

**Issue by garyvdm** [enterprisemodules/partition#4]
`parted mkfs` was removed in parted 3.0 

`Remove all FS-related (file system-related) sub-commands; these commands
  are no longer recognized because they were all dependent on parted "knowing"
  too much about file system: mkpartfs, mkfs, cp, move, check, resize.
  This change removes not just the user interface bits, but also the
  library functions and nearly all of the underlying FS-munging code.
  The code embedded in Parted by which it knew about those file systems
  was so old, unmaintainable and buggy that while seemingly drastic,
  this change is like removing a gangrenous toe.`
http://savannah.gnu.org/forum/forum.php?forum_id=6837

It would be great if an alternative could be provided, so that one could continue to use this module on systems with newer versions of parted.

**Comment by hajee** [comment]
Thank you for bringing this to my attention. I will look into it.

**Comment by hajee** [comment]
I have created a new branch for parted 3 development. Right now it contains an **untested** fix for your problem. 5d26ad2e8dee112f92411278356c978e5d6dedaf.  Do you have a safe setup where you can try this? Feedback would be appreciated.

I also got the impression that some of the parted fields are aligned different then before. This means the parsing is off. 

parted 3 contains machine parseable output. That is a much better and safer option. I'm going to implement that as well.
