### ISSUE TITLE
Module dead?

### ISSUE THREAD

**Issue by jhg03a** [enterprisemodules/partition#6]
I was looking for a module to handle partition management, and this seems like a reasonable solution.  There are dependency references to the easy_type module which has been removed from github and deprecated in the puppet forge.  As such I was wondering what the plan was for this module.

**Comment by hajee** [comment]
We use the module still heavily together with our commercial modules. Easy_type is the engine of a lot of those modules. I'm guessing it will still work with the older version still available on the forge, but no guaranties.
