### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by Ganneff** [enterprisemodules/partition#9]
Hi

the docs say

> This module is based on easy_type. So you need to install easy_type, and this module

but the link doesn't work, so the module is unusable. And it appears one can't (easily?) find it elsewhere.

Could you please provide easy_type again?

Thanks!

Ganneff

**Comment by hajee** [comment]
The open source easy_type is not maintained anymore. You can use the [commercial one](https://forge.puppet.com/enterprisemodules/easy_type). If you don't need any support, we can provide you with a free license for  the partition type. If you do need support, please contact us.

**Comment by Ganneff** [comment]
Hi

sorry for the delay in replying, busy.
The commercial one form puppetforge just links to a 404 page from github again...

I do not need any support, just that one module. :)

Ganneff

**Comment by hajee** [comment]
You can use the one from the forge:

```
$ puppet module install enterprisemodules-easy_type
```

Send me an email bert.hajee@enterprisemodules.com so I have your email and I will send you a license for usage.
